project:
  type: website
  output-dir: docs

website:
  title: "Anabella Molina"
  navbar:
    left:
      - href: index.qmd
        text: Sobre mí
      - href: publications.qmd
        text: Publicaciones
      - href: research.qmd
        text: Investigación
      - href: teaching.qmd
        text: Docencia
      - href: talks.qmd
        text: Charlas
      - href: consultoria.qmd
        text: Consultoria
      - href: gestion.qmd
        text: Gestión 

  site-url: "https://anabellanilom.github.io"
  open-graph:
    image: "images/social-card.png"
  twitter-card:
    image: "images/social-card.png"
    card-style: summary_large_image
    
    right:
      - icon: github
        href: https://github.com/anabellanilom 
      - icon: orcid
        href: "https://orcid.org/0000-0001-7394-8589"
      - icon: linkedin
        href: https://www.linkedin.com/in/draanabellamolina
      - icon: envelope
        href: mailto:anabella.anilom@gmail.com
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=KLz7F4IAAAAJ&hl=es
        target: _blank
        aria-label: Google Scholar
    
  page-footer:
    left: "© 2025 Anabella Molina"
    center: "Hecho con [Quarto](https://quarto.org)"
    right: "Alojado en [GitHub Pages](https://pages.github.com)"

format:
  html:
    theme: cosmo
    toc: true
