project:
  type: website
  output-dir: docs

website:
  title: "Anabella Molina"
  navbar:
    left:
      - href: index.qmd
        text: Short bio
      - href: publications.qmd
        text: Publicaciones
      - href: research.qmd
        text: Investigación
      - href: teaching.qmd
        text: Actividad docente
      - href: networks.qmd
        text: Redes
      - href: talks.qmd
        text: Charlas y presentaciones
      - href: consultoria.qmd
        text: Consultoria
      - href: gestion.qmd
        text: Gestión editorial 
      - href: education.qmd
        text: Educación
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/anabellanilom 
      - icon: linkedin
        href: www.linkedin.com/in/draanabellamolina
      - icon: envelope
        href: mailto:anabella.anilom@gmail.com

format:
  html:
    theme: cosmo
    toc: true
